#build qemu-xj86_64 release
#../configure --extra-cflags="-O3 " --extra-ldflags="-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed" --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/qemu --firmwarepath=/usr/share/qemu:/usr/share/seabios:/usr/lib/ipxe/qemu --localstatedir=/var --disable-blobs --disable-strip --interp-prefix=/etc/qemu-binfmt/%M --with-git-submodules=ignore  --static --disable-system --disable-xen --target-list="x86_64-linux-user"  --enable-lookup-jump-cache --enable-simple-float 

#buid qemu-x86_64 debug
#../configure --extra-cflags="-gdwarf-2 -O0 -g3 " --extra-ldflags="-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed" --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/qemu --firmwarepath=/usr/share/qemu:/usr/share/seabios:/usr/lib/ipxe/qemu --localstatedir=/var --disable-blobs --disable-strip --interp-prefix=/etc/qemu-binfmt/%M --with-git-submodules=ignore  --static --disable-system --disable-xen --target-list="x86_64-linux-user"  --enable-lookup-jump-cache --enable-simple-float 

#buid qemu-x86_64 static
# ../configure --extra-cflags="-O3 --static --static-pie" --extra-ldflags="-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed" --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/qemu --firmwarepath=/usr/share/qemu:/usr/share/seabios:/usr/lib/ipxe/qemu --localstatedir=/var --disable-blobs --disable-strip --interp-prefix=/etc/qemu-binfmt/%M --with-git-submodules=ignore  --static --disable-system --disable-xen --target-list="x86_64-linux-user" --enable-lookup-jump-cache --enable-simple-float

#buid qemu-x86_64 qemu-system-x86 release"
#../configure --extra-cflags="-O2  -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2" --extra-ldflags="-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed" --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/qemu --firmwarepath=/usr/share/qemu:/usr/share/seabios:/usr/lib/ipxe/qemu --localstatedir=/var --disable-blobs --disable-strip --interp-prefix=/etc/qemu-binfmt/%M --enable-user --target-list=x86_64-linux-user,x86_64-softmmu --enable-system --enable-linux-user --disable-xen --enable-modules  --enable-module-upgrades --disable-docs --enable-linux-aio  --enable-attr --disable-brlapi --enable-virtfs --enable-cap-ng --enable-curl --enable-fdt --disable-gnutls --enable-gtk --disable-vte --enable-libiscsi --enable-curses --disable-virglrenderer --disable-opengl --disable-smartcard --disable-vnc-sasl --disable-sdl --enable-spice --disable-rdma --disable-libusb --disable-usb-redir --enable-libssh --enable-nettle --enable-xfsctl --disable-vnc --disable-vnc-jpeg --disable-vnc-png --disable-libpmem --disable-kvm --disable-vhost-net --disable-werror

#buid qemu-x86_64 qemu-system-x86 debug"
#../configure --extra-cflags="-O0 -gdwarf-2 -g3  -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2" --extra-ldflags="-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed" --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/qemu --firmwarepath=/usr/share/qemu:/usr/share/seabios:/usr/lib/ipxe/qemu --localstatedir=/var --disable-blobs --disable-strip --interp-prefix=/etc/qemu-binfmt/%M --enable-user --target-list=x86_64-linux-user,x86_64-softmmu --enable-system --enable-linux-user --disable-xen --enable-modules  --enable-module-upgrades --disable-docs --enable-linux-aio  --enable-attr --disable-brlapi --enable-virtfs --enable-cap-ng --enable-curl --enable-fdt --disable-gnutls --enable-gtk --disable-vte --enable-libiscsi --enable-curses --disable-virglrenderer --disable-opengl --disable-smartcard --disable-vnc-sasl --disable-sdl --enable-spice --disable-rdma --disable-libusb --disable-usb-redir --enable-libssh --enable-nettle --enable-xfsctl --disable-vnc --disable-vnc-jpeg --disable-vnc-png --disable-libpmem --disable-kvm --disable-vhost-net --disable-werror


../configure --extra-cflags="-O0 -g3 -gdwarf-2" --extra-ldflags="-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed" --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/qemu --firmwarepath=/usr/share/qemu:/usr/share/seabios:/usr/lib/ipxe/qemu --localstatedir=/var --disable-blobs --disable-strip --interp-prefix=/etc/qemu-binfmt/%M --with-git-submodules=ignore  --static --disable-system --disable-xen --target-list="x86_64-linux-user"  --enable-reg-opt
