/*
 * Translation Block Statistics Collection
 *
 * Provides performance statistics for TB lookup operations
 */
#ifndef EXEC_TB_STATS_H
#define EXEC_TB_STATS_H

#include "qemu/osdep.h"
#include "qemu/atomic.h"

/*
 * Fine-grained statistics category switches.
 * Each switch can be independently enabled/disabled at compile time.
 * All default to enabled when TB_STATS_ENABLED == 1.
 */

/* Category: TB lookup statistics (lookup_tb_ptr) */
#ifndef TB_STATS_LOOKUP
#define TB_STATS_LOOKUP  0
#endif

/* Category: tb_lookup cache hit/miss detail */
#ifndef TB_STATS_CACHE
#define TB_STATS_CACHE   0
#endif

/* Category: TB generation and execution counts */
#ifndef TB_STATS_GEN
#define TB_STATS_GEN     0
#endif

/*
 * Category: Pre-translation chain depth statistics.
 * Controls: call counts, depth sum/max, hit/miss per step,
 *           and the depth histogram (bucket distribution).
 */
#ifndef TB_STATS_DEPTH
#define TB_STATS_DEPTH   1
#endif

/*
 * Pre-translation depth histogram bucket count.
 * Buckets (by chain depth):
 *   [0] depth  = 0      (no-op: next_pc missing on first step)
 *   [1] depth  = 1
 *   [2] depth  = 2
 *   [3] depth  = 3
 *   [4] depth  = 4-7
 *   [5] depth  = 8-15
 *   [6] depth  = 16-31
 *   [7] depth >= 32
 */
#define TB_PRETRANS_DEPTH_BUCKETS  8

/* Map a chain depth to its histogram bucket index. */
static inline unsigned tb_pretrans_depth_bucket_idx(uint64_t depth)
{
    if (depth <= 3) { return (unsigned)depth; }
    if (depth < 8)  { return 4; }
    if (depth < 16) { return 5; }
    if (depth < 32) { return 6; }
    return 7;
}

/* TB lookup statistics structure */
typedef struct TBLookupStats
{
    /* --- lookup category --- */
    uint64_t lookup_count;   /* Total lookup_tb_ptr calls */
    uint64_t lookup_success; /* Successful TB finds (tb != NULL) */
    uint64_t lookup_miss;    /* Failed TB finds (tb == NULL, return epilogue) */

    /* --- cache category --- */
    uint64_t hit_count_tb_jmp_cache; /* Fast path: found in tb_jmp_cache */
    uint64_t hit_count_qht;          /* Slow path: found in hash table */
    uint64_t fallback_to_dispatcher; /* Not found anywhere, need translation */

    /* --- gen category --- */
    uint64_t tb_gen_count;           /* Total TB generation count (tb_gen_code calls) */
    uint64_t tb_pre_translate_count; /* TBs generated by pre_translate */
    uint64_t tb_exec_count;          /* TB execution count (via dispatcher) */

    /*
     * --- depth category ---
     * Each call to pre_translate() walks a chain of next_pc links.
     * "depth" = number of chain steps taken in a single invocation.
     *
     * Per-step hit/miss:
     *   hit  = the next TB was already in the cache (tb_lookup succeeded)
     *   miss = the next TB had to be freshly generated (tb_gen_code called)
     *
     * hit_rate = pre_translate_lookup_hit / (hit + miss)
     */
    uint64_t pre_translate_calls;        /* Number of pre_translate() invocations */
    uint64_t pre_translate_depth_sum;    /* Sum of chain depths (= hit + miss total) */
    uint64_t pre_translate_depth_max;    /* Maximum observed chain depth */
    uint64_t pre_translate_lookup_hit;   /* Steps where TB was already cached */
    uint64_t pre_translate_lookup_miss;  /* Steps where tb_gen_code was needed */

    /* Depth histogram: bucket[i] counts invocations that fell in bucket i */
    uint64_t pre_translate_depth_buckets[TB_PRETRANS_DEPTH_BUCKETS];
} TBLookupStats;

/* Configuration flags - Force enable for testing */
#if defined(CONFIG_RET_OPT_LOG)
#define TB_STATS_ENABLED 1
#else
#define TB_STATS_ENABLED 0
#endif

/* Statistics macros for zero-overhead in release builds */
#if TB_STATS_ENABLED
#define TB_STAT_INC(field)          qatomic_inc(&g_tb_stats.field)
#define TB_STAT_ADD(field, val)     qatomic_add(&g_tb_stats.field, val)
/*
 * Atomic max: read-CAS loop until our value is stored or a larger one exists.
 * _cur is always initialised at declaration to avoid -Wmaybe-uninitialized.
 * Use distinct names (_cur/_new) to prevent shadowing qatomic_cmpxchg's
 * own internal _old variable, which confuses GCC's uninitialized analysis.
 */
#define TB_STAT_MAX(field, val)                                             \
    do {                                                                    \
        uint64_t _cur = qatomic_read(&g_tb_stats.field);                   \
        uint64_t _new = (uint64_t)(val);                                   \
        while (_new > _cur) {                                               \
            if (qatomic_cmpxchg(&g_tb_stats.field, _cur, _new) == _cur)    \
                break;                                                      \
            _cur = qatomic_read(&g_tb_stats.field);                         \
        }                                                                   \
    } while (0)
#else
#define TB_STAT_INC(field)          do { } while (0)
#define TB_STAT_ADD(field, val)     do { } while (0)
#define TB_STAT_MAX(field, val)     do { } while (0)
#endif

/* Per-category conditional stat macros */
#if TB_STATS_ENABLED && TB_STATS_LOOKUP
#define TB_STAT_LOOKUP_INC(f)       TB_STAT_INC(f)
#else
#define TB_STAT_LOOKUP_INC(f)       do { } while (0)
#endif

#if TB_STATS_ENABLED && TB_STATS_CACHE
#define TB_STAT_CACHE_INC(f)        TB_STAT_INC(f)
#else
#define TB_STAT_CACHE_INC(f)        do { } while (0)
#endif

#if TB_STATS_ENABLED && TB_STATS_GEN
#define TB_STAT_GEN_INC(f)          TB_STAT_INC(f)
#else
#define TB_STAT_GEN_INC(f)          do { } while (0)
#endif

#if TB_STATS_ENABLED && TB_STATS_DEPTH
#define TB_STAT_DEPTH_INC(f)        TB_STAT_INC(f)
#define TB_STAT_DEPTH_ADD(f, v)     TB_STAT_ADD(f, v)
#define TB_STAT_DEPTH_MAX(f, v)     TB_STAT_MAX(f, v)
/* Increment the histogram bucket corresponding to depth d */
#define TB_STAT_DEPTH_BUCKET(d) \
    TB_STAT_DEPTH_INC(pre_translate_depth_buckets[tb_pretrans_depth_bucket_idx(d)])
#else
#define TB_STAT_DEPTH_INC(f)        do { } while (0)
#define TB_STAT_DEPTH_ADD(f, v)     do { } while (0)
#define TB_STAT_DEPTH_MAX(f, v)     do { } while (0)
#define TB_STAT_DEPTH_BUCKET(d)     do { } while (0)
#endif

/* Global statistics instance */
extern TBLookupStats g_tb_stats;

/* API functions */
#if TB_STATS_ENABLED
void tb_stats_init(void);
void tb_stats_reset(void);
TBLookupStats tb_stats_get(void);
void tb_stats_dump(void);
double tb_lookup_success_rate(void);
double tb_cache_hit_rate(void);
double tb_pre_translate_avg_depth(void);
double tb_pre_translate_hit_rate(void);
#else
static inline void tb_stats_init(void) {}
static inline void tb_stats_reset(void) {}
static inline TBLookupStats tb_stats_get(void)
{
    TBLookupStats empty = {0};
    return empty;
}
static inline void tb_stats_dump(void) {}
static inline double tb_lookup_success_rate(void) { return 0.0; }
static inline double tb_cache_hit_rate(void) { return 0.0; }
static inline double tb_pre_translate_avg_depth(void) { return 0.0; }
static inline double tb_pre_translate_hit_rate(void) { return 0.0; }
#endif

#endif /* EXEC_TB_STATS_H */
